/*
 * konvoj_parameterek.h
 *
 *  Created on: 2018. febr. 8.
 *      Author: Roland
 */

#ifndef KONVOJ_PARAMETEREK_H_
#define KONVOJ_PARAMETEREK_H_

#define KONVOJ_JOBB_KOZELEDES_SZERVO_SZOG 39000
#define KONVOJ_BAL_KOZELEDES_SZERVO_SZOG 28000

#define KONVOJ_JOBB_KORRE_MENET_SZERVO_SZOG 29500
#define KONVOJ_BAL_KORRE_MENET_SZERVO_SZOG 37500

#define KONVOJ_JOBB_KOVETES_ELSO_IV 27000
#define KONVOJ_JOBB_KOVETES_MASODIK_IV 39000

#define KONVOJ_BAL_KOVETES_ELSO_IV 36000
#define KONVOJ_BAL_KOVETES_MASODIK_IV 23000

#endif /* KONVOJ_PARAMETEREK_H_ */
